version: '3'

services:

  user-app:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "5000:5000"
      - "5003:5000"
      

  admin-app:
    build:
      context: .
      dockerfile: Dockerfile

    command: python admin_app.py

    ports:
      - "5001:5001"